Mapping
openMetadataInitiative/bids2openminds pull request #1
Opened 2024-02-02 12:40 UTC by Peyman-N

2024-02-16 11:30 UTC, lzehl requested changes

2024-02-16 11:30 UTC, lzehl commented on bids2openminds/mapping.py
> +experimental_approach={
either use plural or singular, but do not mix this for the different dictionaries

2024-02-16 11:30 UTC, lzehl commented on bids2openminds/mapping.py
> +}
remember to add a new line at the end.

2024-02-16 11:30 UTC, lzehl commented on bids2openminds/mapping.py
> +techniques={
I assume that those who are not mapped we do miss at the moment in openMINDS? I can put those on the agenda for the next ontology meeting.

2024-02-16 12:00 UTC, lzehl commented on bids2openminds/mapping.py
> +experimental_approach={
I think we should also follow the constant convention in python here and identify that this is a map:

- MAP_2_EXPERIMENTAL_APPROACHES or
- MAP_TO_EXPERIMENTAL_APPROACHES

2024-02-16 12:02 UTC, lzehl commented on bids2openminds/mapping.py
> +experimental_approaches={
Another suggestion: use the convention to constances in python and add map to distinguish between openminds property names in python module.

Suggestion: MAP_2_EXPERIMENTAL_APPROACHES or MAP_TO_EXPERIMENTAL_APPROACHES

2024-02-16 12:03 UTC, lzehl commented on bids2openminds/mapping.py
> +  "func": "@id: https://openminds.ebrains.eu/instances/experimentalApproach/neuroimaging",
we discussed that this should always be a list

2024-02-23 11:16 UTC, lzehl commented on bids2openminds/mapping.py
> +  "other":["@id: https://openminds.ebrains.eu/instances/biologicalSex/notDetectable"],
other != not detectable !!!

2024-03-28 15:10 UTC, lzehl commented
@Peyman-N this one can be closed no? we would do a new one on the merged code now, correct?

2024-03-28 15:16 UTC, Peyman-N commented
> @Peyman-N this one can be closed no? we would do a new one on the merged code now, correct?

I think we can, but before doing that, I am not sure I have satisfied all of your comments here. So let me check and I would close after I am sure that all of your comments have been addressed.

2024-03-28 15:29 UTC, closed without merging