test
openMetadataInitiative/bids2openminds pull request #32
Opened 2024-04-23 00:51 UTC by Peyman-N

2024-04-29 15:31 UTC, lzehl requested changes
@Peyman-N can you make it PEP8 compliant (at least for the spaces?)

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/main.py
> +def create_dataset_version(bids_layout, dataset_description, layout_df, studied_specimens, file_repository,collection):
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/converter.py
> +    dataset = main.create_dataset(dataset_description, dataset_version,collection)
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/converter.py
> +    [subjects_dict, subject_state_dict, subjects_list] = main.create_subjects(subjects_id, layout_df, bids_layout,collection)
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/converter.py
> +    [files_list, file_repository] = main.create_file(layout_df, input_path,collection)
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/converter.py
> +        bids_layout, dataset_description, layout_df, subjects_list, file_repository,collection
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/converter.py
> +    collection.save(output_path,individual_files=multiple_files,include_empty_properties=include_empty_properties)
spaces missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/main.py
> +def create_dataset(dataset_description, dataset_version,collection):
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/main.py
> +def create_subjects(subject_id, layout_df, layout,collection):
space missing

2024-04-29 15:31 UTC, lzehl commented on bids2openminds/main.py
> +def create_file(layout_df, BIDS_path,collection):
space missing

2024-04-30 11:00 UTC, Peyman-N commented
This pull request has been split into two separate ones (#35 and #34)

2024-04-30 11:00 UTC, closed without merging