Creating a Report for the conversion
openMetadataInitiative/bids2openminds pull request #50
Opened 2024-05-30 12:24 UTC by Peyman-N

2024-06-05 09:12 UTC, lzehl requested changes

2024-06-05 09:12 UTC, lzehl commented on bids2openminds/report.py
> +    print(f"Dataset title : {dataset.full_name}")
you cannot just print the individual elements, but have to write/collect them first into an object that is then printed by executing the function (with option to set to quite) and presented as an output of that function in addition to the collection.

2024-06-05 09:12 UTC, lzehl commented on bids2openminds/report.py
> +    print(f"Dataset title : {dataset.full_name}")
```
Conversion Report
=================

The following elements were converted:
--------------------------------------
+ number of converted subjects: XX
+ number of state for each subject: XX-YY
+ number of files: XX

The following elements were not converted:
------------------------------------------
+ derivative data are ignored for now
+ the following suffixes were not translated to techniques yet: [x,y,z]
```

2024-06-05 09:12 UTC, lzehl commented on bids2openminds/report.py
> +    print(f"Dataset title : {dataset.full_name}")
(this is an example if you decide for a markdown text file, keep the first version simple we can always add more information later on)

2024-06-05 13:43 UTC, Peyman-N commented
@lzehl I modified it as per demand. 
The number of subject states for each subject is problematic, as it can vary from subject to subject. What are your thoughts on this: should we present the average number, the total number of subjects, or perhaps a list of subjects with their respective number of states?
Here is a example of report file.
![Screenshot from 2024-06-05 14-47-45](https://github.com/openMetadataInitiative/bids2openminds/assets/56264166/187dd245-ab17-4485-8ac1-3b2ef220406a)

2024-06-17 12:48 UTC, Peyman-N commented
It should have a sentence specifying the authors should double checked, and list all the authors as they have been extracted.

2024-06-21 13:28 UTC, merged