Creating File bundles
openMetadataInitiative/bids2openminds pull request #51
Opened 2024-05-30 12:24 UTC by Peyman-N

2024-06-05 08:46 UTC, lzehl requested changes

2024-06-05 08:46 UTC, lzehl commented on bids2openminds/main.py
> +def create_file_bundle(path, collection, parent_file_bundle=None):
this seems to run on the full path with no exceptions which means that the dataset folder itself is registered as a file bundle which it should not.

reminder: if you store the openminds results within the dataset directory the code would also register this folder as a filebundle (if run second time) which it should not

2024-06-05 08:46 UTC, lzehl commented on bids2openminds/main.py
> +        name = name[1:]
reduce to "sub-01_ses-01_anat" (not whole path)

2024-06-05 08:46 UTC, lzehl commented on bids2openminds/main.py
> +        name = name[1:]
this example would mean that there is also a filebundle for "sub-01" and "sub-01_ses-01"

2024-06-05 08:46 UTC, lzehl commented on bids2openminds/main.py
> +    openminds_file_bundle = omcore.FileBundle(content_description=f"File bundle created for {str(path)}",
also reduce to name (with replace _ with /)

2024-06-05 08:46 UTC, lzehl commented on test/test_file_bundle.py
> +from bids2openminds.main import create_file_bundle
if test is based on code above the assumed file bundle number is wrong (one less for the not needed dataset file bundle, and another (potentially) one less for the not needed tracking of the openminds folder which does not belong to the BIDS structure)

2024-06-13 15:05 UTC, apdavison commented
This PR needs more tests:
- test_bids_examples.py should be extended to count file bundles
- test_file_bundle.py should be extended to explicitly test the various scenarios mentioned in #49

2024-06-19 08:39 UTC, merged