Creating protocol
openMetadataInitiative/bids2openminds pull request #52
Opened 2024-05-30 14:32 UTC by Peyman-N

2024-06-03 06:13 UTC, lzehl requested changes
maybe this just requires clarification. please check.

2024-06-03 06:13 UTC, lzehl commented on bids2openminds/converter.py
> +    behavioral_protocols, behavioral_protocols_dict = main.create_behavioral_protocol(
I don't understand the double output. Why do you need that?

2024-06-03 06:13 UTC, lzehl commented on test/test_example_datasets_click.py
> +(test_data_set, number_of_openminds_files) = ("ds003", 101)
there should be a test that checks for the number of tasks (at least)

2024-06-05 08:51 UTC, lzehl commented on bids2openminds/converter.py
> +    behavioral_protocols, behavioral_protocols_dict = main.create_behavioral_protocol(
note: only create dict and create list from that on demand

2024-06-05 08:51 UTC, lzehl commented on bids2openminds/converter.py
> +    behavioral_protocols, behavioral_protocols_dict = main.create_behavioral_protocol(
dont change this now, raise issue for a code cleanup for the second release

2024-06-05 08:51 UTC, lzehl commented on test/test_example_datasets_click.py
> +(test_data_set, number_of_openminds_files) = ("ds003", 101)
leave it for later if this takes too much time now

2024-06-13 15:09 UTC, apdavison requested changes
`test_bids_examples.py` needs to be updated

2024-06-17 10:42 UTC, merged