Adding content type to file repository and clarifying version of NIFTI for files
openMetadataInitiative/bids2openminds pull request #53
Opened 2024-06-03 06:36 UTC by Peyman-N

2024-06-05 08:56 UTC, lzehl approved these changes
@apdavison looks okay to me

2024-06-05 09:01 UTC, lzehl commented
only comment: for not trying to load dummy files instead of setting an arbitrary file size you could also make use of the try/except functionality in python

2024-06-13 15:16 UTC, apdavison requested changes

2024-06-13 15:16 UTC, apdavison commented on bids2openminds/utility.py
> +    except:
you should never use a bare `except`. What kind of exception(s) can happen here?

2024-06-13 15:16 UTC, apdavison commented on bids2openminds/main.py
> +from .utility import table_filter, pd_table_value, file_hash, file_storage_size, detect_nifti_verstion
typo: verstion --> version

2024-06-17 10:41 UTC, merged